[build]
target = "x86_64-the_heap.json"

[target.x86_64-the_heap]
runner = "bootimage runner"
linker = "rust-lld"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

