[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
slaballoc = { path = "../slaballoc" }
fat32_parser = { path = "../fat32" }

[package.metadata.bootimage]
run-args = ["-serial", "stdio"]
test-args = ["-serial", "stdio"]
test-success-exit-code = 16
