[alias]
kbuild = "build -p kernel --target x86_64-the_heap.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
krun   = "run   -p kernel --target x86_64-the_heap.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"
kboot  = "bootimage -p kernel --target x86_64-the_heap.json -Z build-std=core,alloc,compiler_builtins -Z build-std-features=compiler-builtins-mem"

[target.x86_64-the_heap]
runner = "bootimage runner"
linker = "rust-lld"
